[[plugins]]
repo = 'Shougo/dein.vim'

# [[plugins]]
# repo = 'lambdalisue/vim-pyenv'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  " 隠しファイルをデフォルトで表示させる
  let g:NERDTreeShowHidden=1
  " ブックマークや、ヘルプのショートカットをメニューに表示しない
  let g:NERDTreeMinimalUI=1
  " treeの見た目
  let g:NERDTreeDirArrowExpandable='+'
  let g:NERDTreeDirArrowCollapsible='-'
  " 表示する位置
  let g:NERDTreeWinPos='left'

  " keymap
  nnoremap :tree :NERDTreeToggle
  nnoremap <silent><C-e> :NERDTreeToggle<CR>

  " autocmd
  " NERDTree File highlighting
  function! NERDTreeHighlightFile(extension, fg, bg, guifg, guibg)
    exec 'autocmd FileType nerdtree highlight '. a:extension .' ctermbg='. a:bg .' ctermfg='. a:fg .' guibg='. a:guibg .' guifg='. a:guifg
    exec 'autocmd FileType nerdtree syn match '. a:extension .' #^\s\+.*'. a:extension .'$#'
    exec 'autocmd FileType nerdtree syn match '. a:extension .' #^\s\+.*'. a:extension .'\*$#'
  endfunction

  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('md',     'blue',    'none', '#b7ddff', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('sh',     'yellow',  'none', '#b7ffe6', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('bat',    'yellow',  'none', '#b7ffe6', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('json',   'yellow',  'none', '#b7ffe6', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('yml',    'yellow',  'none', '#b7ffe6', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('toml',   'yellow',  'none', '#b7ffe6', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('vim',    'yellow',  'none', '#b7ffe6', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('config', 'yellow',  'none', '#b7ffe6', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('conf',   'yellow',  'none', '#b7ffe6', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('ini',    'yellow',  'none', '#b7ffe6', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('html',   'green',   'none', '#ffc5b7', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('pug',    'green',   'none', '#ffc5b7', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('jade',   'green',   'none', '#ffc5b7', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('vue',    'green',   'none', '#b7ffb8', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('jsx',    'green',   'none', '#b7ffb8', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('tag',    'green',   'none', '#b7ffb8', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('styl',   'cyan',    'none', '#ffe6b7', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('css',    'cyan',    'none', '#ffe6b7', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('scss',   'cyan',    'none', '#ffe6b7', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('sass',   'cyan',    'none', '#ffe6b7', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('rb',     'red',     'none', '#fdffb7', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('js',     'red',     'none', '#fdffb7', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('ts',     'red',     'none', '#fdffb7', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('tsx',    'red',     'none', '#fdffb7', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('py',     'red',     'none', '#fdffb7', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('php',    'magenta', 'none', '#e6b7ff', '#151515')
  autocmd VimEnter,Colorscheme * call NERDTreeHighlightFile('go',     'magenta', 'none', '#e6b7ff', '#151515')

  " 初期表示に関わるコマンド
  autocmd BufEnter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
  " デフォルトでツリーを表示させる
  " autocmd VimEnter,Colorscheme * NERDTree
  " ファイル指定がない場合は表示させずにctrlpを優先させる
  autocmd VimEnter,Colorscheme * if argc() != 0 | NERDTree | endif
  " カーソルをメインウインドウに移動
  autocmd VimEnter,Colorscheme * if argc() != 0 | wincmd p | endif
'''

# [[plugins]]
# repo = 'Xuyuanp/nerdtree-git-plugin'
# depends = ['scrooloose/nerdtree']
# hook_add = '''
#   let g:NERDTreeIndicatorMapCustom={
#    \ "Modified"  : "✹",
#    \ "Staged"    : "✚",
#    \ "Untracked" : "✭",
#    \ "Renamed"   : "➜",
#    \ "Unmerged"  : "═",
#    \ "Deleted"   : "✖",
#    \ "Dirty"     : "✗",
#    \ "Clean"     : "✔︎",
#    \ 'Ignored'   : '☒',
#    \ "Unknown"   : "?"
#    \ }
# '''

# [[plugins]]
# repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
# hook_add = '''
#   " let g:NERDTreeLimitedSyntax=1
#
#   let g:NERDTreeFileExtensionHighlightFullName=1
#   let g:NERDTreeExactMatchHighlightFullName=1
#   let g:NERDTreePatternMatchHighlightFullName=1
#
#   let g:NERDTreeHighlightCursorline=0
#
#   let g:NERDTreeSyntaxEnabledExtensions=['toml']
# '''

[[plugins]]
repo = 'thinca/vim-qfreplace'

[[plugins]]
repo = 'mileszs/ack.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
  " # ctrlpバッファに入る時と出るときに使用する関数を定義
  " # lightline.vimで表示しているステータスラインとの衝突を避けるため
  let g:ctrlp_buffer_func={
    \ 'enter': 'CtrlPEnter',
    \ 'exit': 'CtrlPLeave',
  \ }

  " # ctrlpに入るとき，ステータスラインの表示をoffに
  function! CtrlPEnter()
    set laststatus=0
  endfunction

  " # ctrlpから出るとき，ステータスラインの表示をonに
  function! CtrlPLeave()
    set laststatus=2
  endfunction

  " # ファイルを指定せずにvimを立ち上げた時に，自動的にctrlpを起動する
  function CtrlPIfEmpty()
    if @% == ""
      CtrlP ~/
    endif
  endfunction

  augroup AutoCtrlP
    autocmd!
    autocmd VimEnter * call CtrlPIfEmpty()
  augroup END

  " # ctrlpのキーマッピングを <C-p>から<Leader>eに変更
  " # yankround.vimで<C-p>を使用しているため，衝突回避
  " let g:ctrlp_map='<nop>'
  " nnoremap <Leader>e :CtrlP ~/<CR>

  " # 日本語検索をoff
  " let g:ctrlp_use_migemo=0
  " # あいまい検索をoff
  let g:ctrlp_regexp=1
  " # キャッシュを使用して検索を高速化
  let g:ctrlp_use_caching=1
  " # vim終了時にキャッシュをクリアしない
  let g:ctrlp_clear_cache_on_exit=0
  " # <C-r>でキャッシュをクリアして再検索
  let g:ctrlp_prompt_mappings={'PrtClearCache()': ['<C-r>']}
  " # 検索の際に200[ms]のウェイトを入れる
  let g:ctrlp_lazy_update=200
  " # 検索結果の表示ウィンドウの設定、10件分を表示、それ以上はスクロール
  let g:ctrlp_match_window='bottom,order:btt,min:1,max:20,results:50'
  " # 隠しファイルを表示しない
  " let g:ctrlp_show_hidden=0
  " # 検索してほしくないファイルやディレクトリを除外
  let g:ctrlp_custom_ignore={
    \ 'dir':  '\v[\/]\.(git|hg|svn)$',
    \ 'file': '\v\.(exe|so|dll|o)$',
    \ 'link': 'some_bad_symbolic_links',
  \ }
'''

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
  let g:winresizer_gui_enable=1
  let g:winresizer_vert_resize=1
  let g:winresizer_horiz_resize=1
  let g:winresizer_start_key='<C-T>'
  let g:winresizer_gui_start_key='<C-T>'
'''

# [[plugins]]
# repo = 'mhinz/vim-startify'

# [[plugins]]
# repo = 'ryanoasis/vim-devicons'
# hook_add = '''
#   set encoding=UTF-8
#   let g:WebDevIconsUnicodeDecorateFolderNodes=1
# '''

# [[plugins]]
# repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
# # depends = ['vim-devicons', 'scrooloose/nerdtree']
# depends = ['scrooloose/nerdtree']
# hook_add = '''
#   let g:NERDTreeLimitedSyntax=1
#   " let g:NERDTreeSyntaxDisableDefaultExtensions = 1
# '''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  " let g:gitgutter_highlight_lines=1
  let g:gitgutter_max_signs=9999
  set updatetime=100
  " highlight clear SignColumn
  autocmd ColorScheme * hi GitGutterAdd guifg=#009900
  autocmd ColorScheme * hi GitGutterChange guifg=#bbbb00
  autocmd ColorScheme * hi GitGutterDelete guifg=#ff2222
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'osyo-manga/vim-over'
hook_add = '''
  " 全体置換
  nnoremap <silent> <Space>o :OverCommandLine<CR>%s//g<Left><Left>
  " 選択範囲置換
  vnoremap <silent> <Space>o :OverCommandLine<CR>s//g<Left><Left>
  " カーソル下の単語置換
  nnoremap sub :OverCommandLine<CR>%s/<C-r><C-w>//g<Left><Left>
'''

[[plugins]]
repo = 'terryma/vim-multiple-cursors'
hook_add = '''
  " Called once right before you start selecting multiple cursors
  function! Multiple_cursors_before()
    let g:ycm_auto_trigger = 0
    if exists(':NeoCompleteLock') == 2
      exe 'NeoCompleteLock'
    endif
  endfunction

  " Called once only when the multiple selection is canceled (default <Esc>)
  function! Multiple_cursors_after()
    let g:ycm_auto_trigger = 1
    if exists(':NeoCompleteUnlock') == 2
      exe 'NeoCompleteUnlock'
    endif
  endfunction
'''

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  " mapping
  nmap n <Plug>(anzu-n-with-echo)
  nmap N <Plug>(anzu-N-with-echo)
  nmap * <Plug>(anzu-star-with-echo)
  nmap # <Plug>(anzu-sharp-with-echo)
  " clear status
  nmap <Esc><Esc> <Plug>(anzu-clear-search-status)
  " statusline
  set statusline=%{anzu#search_status()}
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'justincampbell/vim-eighties'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  let g:quickrun_config = {'*': {'hook/time/enable': '1'}}
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd='tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd='make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd='gmake'
  else
    let cmd='make'
  endif
  let g:dein#plugin.build=cmd
'''

[[plugins]]
repo = 'Shougo/vimshell.vim'
hook_add = '''
" vimshell setting
let g:vimshell_interactive_update_time = 10
let g:vimshell_prompt = $USERNAME."% "
let g:vimshell_user_prompt = 'getcwd()'

" vimshell map
nnoremap <silent> vs :VimShell<CR>
nnoremap <silent> vsc :VimShellCreate<CR>
nnoremap <silent> vsp :VimShellPop<CR>
nnoremap <silent> vsi :VimShellInteractive<CR>
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# カーソル移動
[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add = '''
  " デフォルトのキーマッピングを無効に
  let g:EasyMotion_do_mapping=0
  " f + 2文字 で画面全体を検索してジャンプ
  nmap f <plug>(easymotion-overwin-f2)
  " 検索時、大文字小文字を区別しない
  let g:EasyMotion_smartcase=1
'''

# カーソル位置のコンテキストに合わせてftを切り替える
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

# カーソル位置のコンテキストのftを判定するライブラリ
[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  " vim立ち上げたときに、自動的にvim-indent-guidesをオンにする
  let g:indent_guides_enable_on_vim_startup=1
  " ガイドをスタートするインデントの量
  let g:indent_guides_start_level=2
  " 自動カラーを無効にする
  let g:indent_guides_auto_colors=0
  " ハイライト色の変化の幅
  let g:indent_guides_color_change_percent=30
  " ガイドの幅
  let g:indent_guides_guide_size=1
  " 奇数インデントのカラー
  autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd guibg=#223344 ctermbg=153
  " 偶数インデントのカラー
  autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=#443322 ctermbg=221
'''

[[plugins]]
repo = 'ervandew/supertab'
hook_add = '''
  let g:SuperTabDefaultCompletionType="<c-n>"
'''

# comment out/in
[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
  vmap gcc <Plug>(caw:zeropos:toggle)
'''

# markdown syntax
[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['md']

# pug syntax
[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['pug', 'jade']

# html5 syntax
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

# stylus syntax
[[plugins]]
repo = 'wavded/vim-stylus'
on_ft = ['stylus']

# scss color syntax
[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = ['sass']

# css syntax
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'stylus', 'sass', 'less', 'scss']

# css color syntax
[[plugins]]
repo = 'ap/vim-css-color'
on_ft = ['css', 'stylus', 'sass', 'less', 'scss']

# json syntax
[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

# toml syntax
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# vue syntax
[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']
hook_add = '''
  " let g:vue_disable_pre_processors=1
  " autocmd BufRead,BufNewFile *.vue setlocal filetype=vue.html.js.css
  autocmd FileType vue syntax sync fromstart

  let g:ft = ''
  function! NERDCommenter_before()
    if &ft == 'vue'
      let g:ft = 'vue'
      let stack = synstack(line('.'), col('.'))
      if len(stack) > 0
        let syn = synIDattr((stack)[0], 'name')
        if len(syn) > 0
          exe 'setf ' . substitute(tolower(syn), '^vue_', '', '')
        endif
      endif
    endif
  endfunction
  function! NERDCommenter_after()
    if g:ft == 'vue'
      setf vue
      let g:ft = ''
    endif
  endfunction
'''

# javascript syntax
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']
hook_add = '''
  let g:javascript_plugin_jsdoc=1
'''

# es6 syntax
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

# stg-0 syntax
[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = ['javascript']

# jsx syntax
[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['jsx']

#typescript syntax
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']
hook_add = '''
  let g:typescript_indent_disable = 1
'''

# typescript template syntax
[[plugins]]
repo = 'Quramy/vim-js-pretty-template'
on_ft = ['typescript']

# typescript d.ts
[[plugins]]
repo = 'Quramy/vim-dtsm'
on_ft = ['typescript']

# typescript typings
[[plugins]]
repo = 'mhartington/vim-typings'
on_ft = ['typescript']

# typescript complement
[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']

# php syntax
[[plugins]]
repo = 'StanAngeloff/php.vim'
on_ft = ['php']

# go syntax
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

# ruby syntax
[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['rb']

# ruby end
[[plugins]]
repo = 'tpope/vim-endwise'

# python syntax
[[plugins]]
repo = 'hdima/python-syntax'
on_ft = ['py']
hook_add = '''
  let python_highlight_all = 1
'''

# jsdoc conrtol + L
[[plugins]]
repo = 'heavenshell/vim-jsdoc'
hook_add = '''
  let g:jsdoc_allow_input_prompt=1
  let g:jsdoc_input_description=1
  let g:jsdoc_allow_shorthand=1
  let g:jsdoc_enable_es6=1
  nmap <silent> <C-l> <Plug>(jsdoc)
'''

# emmet html:5 <c-y>,
[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
  let g:user_emmet_settings={
  \    'variables': {
  \      'lang': 'ja'
  \    },
  \   'indentation': '  '
  \ }
'''

 # カラースキーマ
[[plugins]]
repo = 'Pychimp/vim-luna'
hook_add = '''
  set background=dark
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  autocmd MyAutoCmd VimEnter * nested colorscheme luna
'''

# statusline custom
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline={
  \   'active': {
  \     'left': [['mode', 'paste'], ['gitbranch', 'readonly', 'filename', 'modified']],
  \     'right': [['lineinfo'], ['percent'], ['fileformat', 'fileencoding', 'filetype']]
  \   },
  \   'inactive': {
  \     'left': [['filename']],
  \     'right': [['lineinfo'], ['percent']]
  \   },
  \   'component_function': {
  \     'gitbranch': 'fugitive#head'
  \   }
  \ }
'''

# linter, hint
[[plugins]]
repo = 'w0rp/ale'
depends = ['lightline.vim']
hook_add = '''
  let g:ale_statusline_format=['E%d', 'W%d', '']
  let g:ale_linter_aliases = {
  \   'vue': 'css'
  \ }
  let g:ale_linters = {
  \   'html': ['htmlhint'],
  \   'pug': ['puglint'],
  \   'css': ['stylelint'],
  \   'stylus': ['stylelint'],
  \   'javascript': ['eslint'],
  \   'vue': ['eslint'],
  \   'jsx': ['eslint']
  \ }
  nmap <silent> <C-w>j <Plug>(ale_next_wrap)
  nmap <silent> <C-w>k <Plug>(ale_previous_wrap)
'''

# lightline ale
[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = ['lightline.vim']
hook_add = '''
  let g:lightline.component_expand={
  \   'linter_warnings': 'lightline#ale#warnings',
  \   'linter_errors': 'lightline#ale#errors',
  \   'linter_ok': 'lightline#ale#ok'
  \ }
  let g:lightline.component_type={
  \   'linter_warnings': 'warning',
  \   'linter_errors': 'error',
  \   'linter_ok': 'left'
  \ }
  let g:lightline.active.right=[['lineinfo'], ['percent'], ['fileformat', 'fileencoding', 'filetype'], ['linter_errors', 'linter_warnings', 'linter_ok']]
'''

